apiVersion: v2
name: backend-app
description: Basic helm chart for express-backend application
type: application
version: 0.1.0
appVersion: "1.16.0"

# dependencies:
#   - name: ingress-nginx
#     version: "4.10.0"
#     repository: "https://kubernetes.github.io/ingress-nginx"