deployment: 
  enabled: true
  replicaCount: 3
  image:
    repository: "deependraparmar1/backend"
    tag: "latest"
    pullPolicy: "IfNotPresent"
    port: 4000

service:
  enabled: true
  type: "NodePort"
  port: 80
  targetPort: 4000
  nodePort: 32001

ingress: 
  enabled: true
  name: "ingress"
  host: "example.com"
  className: "nginx"

ingress-nginx:
  controller:
    enabled: true

statefulset:
  enabled: true
  name: "postgres"
  replicas: 2
  image: "postgres"
  tag: "latest"
  port: 5432
  volume: true
  volumeClaimName: "postgres-volume"
  storage: "1Gi"
  mountPath: "/var/lib/postgresql/data"

  service:
    name: "postgres"
    port: 5432
  
istio:
  gateway:
    enabled: true
    host: "example.com"
    port: 80
    protocol: HTTP
    tls:
      secretName: "my-tls-secret"

  virtualService:
    enabled: true
    host: "example.com"

certManager:
  enabled: true

  certificate:
    name: "example-cert"
    secretName: "example-tls"
    issuerName: "letsencrypt-prod"
    issuerKind: "ClusterIssuer"

  issuer:
    create: true
    name: "letsencrypt-prod"
    email: "hello@gmail.com"
    secretName: "letsencrypt-prod"
    gatewayName: "istio-ingressgateway"
    gatewayNamespace: "istio-system"

hpa:
  enabled: true
  targetKind: "Deployment"
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 75
  memoryUtilization: 75

serviceAccount:
  enabled: true