deployment: 
  enabled: true
  replicaCount: 3
  image:
    repository: "deependraparmar1/backend"
    tag: "latest"
    pullPolicy: "IfNotPresent"
    port: 4000

service:
  enabled: true
  type: "NodePort"
  port: 80
  targetPort: 4000
  nodePort: 32001

ingress: 
  enabled: true
  name: "ingress"
  host: "example.com"
  className: "nginx"

ingress-nginx:
  controller:
    enabled: true

statefulset:
  enabled: true
  name: "postgres"
  replicas: 2
  image: "postgres"
  tag: "latest"
  port: 5432
  volume: true
  volumeClaimName: "postgres-volume"
  storage: "1Gi"
  mountPath: "/var/lib/postgresql/data"

  service:
    name: "postgres"
    port: 5432
  
