deployment: 
  enabled: true
  replicaCount: 3
  image:
    repository: "deependraparmar1/backend-app"
    tag: null
    pullPolicy: "IfNotPresent"
    port: 4000

service:
  enabled: true
  type: "NodePort"
  port: 80
  targetPort: 4000
  nodePort: 32001

ingress: 
  enabled: false
  name: "ingress"
  host: "example.com"
  className: "nginx"

ingress-nginx:
  controller:
    enabled: true

statefulset:
  enabled: true
  name: "postgres"
  replicas: 2
  image: "postgres"
  tag: null
  port: 5432
  volume: true
  volumeClaimName: "postgres-volume"
  storage: "1Gi"
  mountPath: "/var/lib/postgresql/data"

  service:
    name: "postgres"
    port: 5432
  
istio:
  gateway:
    enabled: true
    host: "example.com"
    port: 80
    protocol: HTTP
    tls:
      secretName: "my-tls-secret"

  virtualService:
    enabled: true
    host: "example.com"

certManager:
  enabled: true

  certificate:
    name: "example-cert"
    secretName: "example-tls"
    issuerName: "letsencrypt-prod"
    issuerKind: "ClusterIssuer"

  issuer:
    create: true
    name: "letsencrypt-prod"
    email: "hello@gmail.com"
    secretName: "letsencrypt-prod"
    gatewayName: "istio-ingressgateway"
    gatewayNamespace: "istio-system"

hpa:
  enabled: true
  targetKind: "Deployment"
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 75
  memoryUtilization: 75

serviceAccount:
  enabled: true

cronjob:
  enabled: true
  name: "data-cleanup"
  schedule: "0 0 * * *"
  restartPolicy: "OnFailure"
  image:
    repository: busybox
    tag: null
  command: ["/bin/sh", "-c"]
  args: ["echo 'Running scheduled task' && date"]
  env:
    - name: ENVIRONMENT
      value: "production"

dnsEndpoint:
  enabled: true
  host: "app.example.com"
  targetIP: "192.168.1.100"
  ttl: 300 

secret: 
  name: "postgres-secret"
  env:
    - name: POSTGRES_USER
      value: cG9zdGdyZXM=
    - name: POSTGRES_PASSWORD
      value: cGFzc3dvcmQ=