{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificate.name }}
spec:
  secretName: {{ .Values.certManager.certificate.secretName }} 
  issuerRef:
    name: {{ .Values.certManager.certificate.issuerName }}
    kind: {{ .Values.certManager.certificate.issuerKind }}
  dnsNames:
  - {{ .Values.istio.gateway.host }}
{{- end }}
