{{- if .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
spec:
  acme:
    email: {{ .Values.certManager.issuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.secretName }}
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: {{ .Values.certManager.issuer.gatewayName }}
            namespace: {{ .Values.certManager.issuer.gatewayNamespace }}
        port: 80
{{- end }}
