{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      protocol: HTTPS
      name: https
    hosts:
    - {{ .Values.istio.gateway.host }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istio.gateway.tls.secretName | default "default-cert" }}

  - port:
      number: {{ .Values.istio.gateway.port | default 80 }}
      protocol: {{ .Values.istio.gateway.protocol | default "HTTP" }}
      name: http
    hosts:
    - {{ .Values.istio.gateway.host }}
{{- end }}
