{{- if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.istio.gateway.port }}
      protocol: {{ .Values.istio.gateway.protocol }}
    hosts:
    - {{ .Values.istio.gateway.host }}
{{- end }}
