apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}

    {{- with .Values.service }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    {{- end }}