{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}

    {{- with .Values.service }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    {{- end }}
{{- end }}

---

{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulset.service.name }}-service
  labels:
    app: {{ .Values.statefulset.name }}
spec:
  ports:
    - port: {{ .Values.statefulset.service.port }}
      name: http
  clusterIP: None
  selector:
    app: {{ .Values.statefulset.name }}
{{- end}}