apiVersion: v1
kind: Service
metadata:
  {{- with .Values.statefulset.service }}
  name: {{ .name }}-service
  labels:
    app: {{ .name }}
spec:
  ports:
  - port: {{ .port }}
    name: {{ .name }}
  clusterIP: None
  selector:
    app: {{ .name }}
  {{- end}}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}-statefulset
spec:
  selector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  serviceName: {{ .Values.statefulset.service.name }}-service
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.name }}
    spec:
      containers:
      - name: {{ .Values.statefulset.name }}
        image: "{{ .Values.statefulset.image }}:{{ .Values.statefulset.tag }}"
        ports:
        - containerPort: {{ .Values.statefulset.port }}
        volumeMounts:
        - name: {{ .Values.statefulset.volumeMountName }}
          mountPath: {{ .Values.statefulset.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.statefulset.volumeMountName }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
