{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-virtualservice
spec:
  hosts:
  - {{ .Values.istio.virtualService.host }}
  gateways:
  - {{ .Chart.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Chart.Name }}-service
        port:
          number: {{ .Values.service.port }}
{{- end }}
