name: Update Helm Chart with Latest Docker Image Tag

on:
  push:
    branches:
      - main
      - "feat/*"
  pull_request:
    branches:
      - main
      - "feat/*"

permissions:
  contents: write

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get Latest Image Tag from Docker Hub
        id: get_latest_tag
        run: |
          IMAGE_NAME="deependraparmar1/backend-app"

          RESPONSE=$(curl -s -H "Authorization: bearer ${{ secrets.DOCKER_ACCESS_TOKEN }}" "https://registry.hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/")

          # Adjust the index as needed; this assumes results[0] has the latest tag
          TAG=$(jq -r '.results[1].name')

          if [ -z "$TAG" ]; then
            echo "Failed to retrieve the latest tag. Response: $RESPONSE"
            exit 1
          fi

          echo "Latest Docker tag: $TAG"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Update Helm Chart values.yaml with latest tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.LATEST_TAG }}/" values.yaml
          

      - name: Commit and Push the updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ env.LATEST_TAG }}"
          git push origin main
